

package com.axeldev.automovil.igu;

import com.axeldev.automovil.logica.Automovil;
import com.axeldev.automovil.logica.Controladora;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ConsultaAutomovil extends javax.swing.JFrame {

    Controladora control = new Controladora();
    
    /** Creates new form ConsultaAutomovil */
    public ConsultaAutomovil() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerConsultas = new javax.swing.JPanel();
        labelTitleConsulta = new javax.swing.JLabel();
        containerTableAndBtns = new javax.swing.JPanel();
        containerTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelTitleConsulta.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelTitleConsulta.setText("Consultar Automóviles");

        containerTableAndBtns.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        containerTable.setViewportView(table);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerTableAndBtnsLayout = new javax.swing.GroupLayout(containerTableAndBtns);
        containerTableAndBtns.setLayout(containerTableAndBtnsLayout);
        containerTableAndBtnsLayout.setHorizontalGroup(
            containerTableAndBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTableAndBtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerTable, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(containerTableAndBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        containerTableAndBtnsLayout.setVerticalGroup(
            containerTableAndBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTableAndBtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerTable, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(containerTableAndBtnsLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerConsultasLayout = new javax.swing.GroupLayout(containerConsultas);
        containerConsultas.setLayout(containerConsultasLayout);
        containerConsultasLayout.setHorizontalGroup(
            containerConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerConsultasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitleConsulta)
                .addGap(187, 187, 187))
            .addGroup(containerConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerTableAndBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        containerConsultasLayout.setVerticalGroup(
            containerConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitleConsulta)
                .addGap(18, 18, 18)
                .addComponent(containerTableAndBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (table.getRowCount() > 0) {
            if (table.getSelectedRow() != -1) {
                int id = Integer.parseInt(String.valueOf(table.getValueAt(table.getSelectedRow(), 0)));
                control.borrarAuto(id);
                mostrarMensaje("Auto borrado correctamente!", "Info", "Borrado exitoso!");
                cargarTabla();
            } else {
                mostrarMensaje("No hay seleccionada ninguna fila", "Error", "Fila no encontrada!");
            }
        } else {
            mostrarMensaje("No se encontro ningun automovil", "Error", "Tabla vacia!");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (table.getRowCount() > 0) {
            if (table.getSelectedRow() != -1) {
                int id = Integer.parseInt(String.valueOf(table.getValueAt(table.getSelectedRow(), 0)));
                EditarAutomovil editar = new EditarAutomovil(id);
                editar.setVisible(true);
                editar.setLocationRelativeTo(null);
                this.dispose();
            } else {
                mostrarMensaje("No hay seleccionada ninguna fila", "Error", "Fila no encontrada!");
            }
        } else {
            mostrarMensaje("No se encontro ningun automovil", "Error", "Tabla vacia!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel containerConsultas;
    private javax.swing.JScrollPane containerTable;
    private javax.swing.JPanel containerTableAndBtns;
    private javax.swing.JLabel labelTitleConsulta;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        DefaultTableModel modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        String titulos[] = {
            "Id",
            "Modelo",
            "Marca",
            "Motor",
            "Color",
            "Patente",
            "Nro. Puertas"
        };
        modeloTabla.setColumnIdentifiers(titulos);
        
        List<Automovil> automoviles = control.traerAutomoviles();
        if(automoviles != null){
            for (Automovil automovil : automoviles) {
                Object[] object = {
                    automovil.getId(),
                    automovil.getModelo(),
                    automovil.getMarca(),
                    automovil.getMotor(),
                    automovil.getColor(),
                    automovil.getPatente(),
                    automovil.getNroPuertas()
                };
                
                modeloTabla.addRow(object);
            }
        }
        
        table.setModel(modeloTabla);
    }
    
    public void mostrarMensaje(String message, String type, String title){
        JOptionPane optionPane = new JOptionPane(message);
        if(type.equalsIgnoreCase("Info")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        }
        else if(type.equalsIgnoreCase("Error")){
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog = optionPane.createDialog(title);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }

}
